#!/usr/bin/awk -f
BEGIN {
    print "-- generated by flatten-deps.awk"
    build_id = ""
    root_done = 0
    child_level = 0
}
function sql_escape(s) {
    gsub(/'/, "''", s)
    return s
}
function field_value(line, key,    tmp, pat) {
    pat = "\"" key "\"[[:space:]]*:[[:space:]]*\""
    if (index(line, "\"" key "\"") == 0) {
        return ""
    }
    tmp = line
    sub("^.*" pat, "", tmp)
    sub("\".*$", "", tmp)
    return tmp
}
function emit_node(key, parent, ord) {
    parent_sql = (parent == "" ? "NULL" : "'" sql_escape(parent) "'")
    print "INSERT INTO dependency_nodes (node_key, build_id, parent_key, group_id, artifact_id, version, scope, ordinal) VALUES ('" \
        sql_escape(key) "', '" sql_escape(build_id) "', " parent_sql ", '" \
        sql_escape(cur_group) "', '" sql_escape(cur_artifact) "', '" sql_escape(cur_version) "', '" \
        sql_escape(cur_scope) "', " ord ");"
}
function finalize_node(    key, parent, ord) {
    if (cur_group == "" || cur_artifact == "" || cur_version == "" || cur_scope == "") {
        return
    }
    if (!root_done) {
        coord = cur_group ":" cur_artifact ":" cur_version
        print "INSERT INTO builds (id, root_coordinate) VALUES ('" sql_escape(build_id) "', '" sql_escape(coord) "');"
        emit_node("root", "", 0)
        parent_key[0] = "root"
        child_ord[0] = 0
        root_done = 1
        return
    }
    parent = parent_key[child_level - 1]
    ord = child_ord[child_level - 1]
    key = parent "/" ord
    child_ord[child_level - 1]++
    parent_key[child_level] = key
    emit_node(key, parent, ord)
}
/"buildId"/ {
    val = field_value($0, "buildId")
    if (val != "") {
        build_id = val
    }
}
/"groupId"/ {
    if ($0 ~ /"children"/) {
        next
    }
    cur_group = field_value($0, "groupId")
    cur_artifact = ""
    cur_version = ""
    cur_scope = ""
}
/"artifactId"/ {
    val = field_value($0, "artifactId")
    if (val != "") {
        cur_artifact = val
    }
}
/"version"/ {
    val = field_value($0, "version")
    if (val != "" && $0 !~ /"children"/) {
        cur_version = val
    }
}
/"scope"/ {
    val = field_value($0, "scope")
    if (val != "") {
        cur_scope = val
        finalize_node()
    }
}
/"children"[[:space:]]*:[[:space:]]*\[[[:space:]]*\]/ {
    next
}
/"children"[[:space:]]*:[[:space:]]*\[/ {
    child_level++
    if (!(child_level - 1 in child_ord)) {
        child_ord[child_level - 1] = 0
    }
}
/^[[:space:]]*\],?[[:space:]]*$/ {
    if (child_level > 0) {
        child_level--
    }
}
