"""Milestone 1 verifier — the decoded waiver register at /app/out/waivers.json.

Run alone with: pytest tests/test_m1.py
"""

import json
import pathlib
import subprocess

import jsonschema
import pytest

HERE = pathlib.Path(__file__).resolve().parent
OUT = pathlib.Path("/app/out/waivers.json")
SCHEMA = pathlib.Path("/app/schema/waivers.schema.json")
EXPECTED = HERE / "expected_waivers.json"
MAIN_CLASS_REL = pathlib.Path("com/mariner/audit/Main.class")


def _class_dir() -> pathlib.Path | None:
    candidates = [pathlib.Path("/app/classes"), pathlib.Path("/app/pipeline/classes")]
    candidates.extend(sorted(pathlib.Path("/app").glob("*/classes")))
    for candidate in candidates:
        if (candidate / MAIN_CLASS_REL).exists():
            return candidate
    return None


def _run_stage(stage: str) -> None:
    class_dir = _class_dir()
    assert class_dir is not None, "missing compiled com.mariner.audit.Main class under /app"
    subprocess.run(
        ["java", "-cp", f"{class_dir}:/app/lib/*", "com.mariner.audit.Main", stage],
        cwd="/app",
        check=True,
        timeout=45,
    )


def _load(path: pathlib.Path):
    return json.loads(pathlib.Path(path).read_text())


@pytest.fixture(scope="module")
def produced():
    _run_stage("decode")
    assert OUT.exists(), f"{OUT} was not produced"
    return _load(OUT)


@pytest.fixture(scope="module")
def expected():
    return _load(EXPECTED)


class TestMilestone1Decode:
    """Milestone 1: decode the waiver register from the narrative report."""

    def test_java_pipeline_entrypoint_exists(self) -> None:
        """Milestone output must be generated by the reusable Java CLI pipeline."""
        assert _class_dir() is not None, "missing compiled com.mariner.audit.Main class under /app"

    def test_output_is_a_list(self, produced) -> None:
        """waivers.json must be a JSON array of per-service waiver records."""
        assert isinstance(produced, list), "waivers.json must be a JSON array"

    def test_conforms_to_schema(self, produced) -> None:
        """Every record must satisfy the published waiver register schema."""
        schema = _load(SCHEMA)
        jsonschema.Draft202012Validator(schema).validate(produced)

    def test_covers_every_service(self, produced, expected) -> None:
        """The register must contain exactly the in-scope services, once each."""
        got = [r["service_id"] for r in produced]
        want = [r["service_id"] for r in expected]
        assert sorted(got) == sorted(want), "service set differs from inventory"
        assert len(got) == len(set(got)), "duplicate service rows present"

    def test_revoked_waivers_are_detected(self, produced, expected) -> None:
        """Waivers rescinded later in the narrative must read as revoked.

        A decoder that only reads grant lines would mislabel these as granted.
        """
        exp = {r["service_id"]: r for r in expected}
        got = {r["service_id"]: r for r in produced}
        revoked = [sid for sid, r in exp.items() if r["status"] == "revoked"]
        assert revoked, "fixture sanity: expected at least one revoked waiver"
        for sid in revoked:
            assert got[sid]["status"] == "revoked", f"{sid} should be revoked"
            assert got[sid]["revoked_on"] == exp[sid]["revoked_on"], (
                f"{sid} revoked_on mismatch"
            )

    def test_replacement_waiver_survives_old_rescission(self, produced) -> None:
        """A rescinded older waiver must not revoke the later replacement waiver."""
        got = {r["service_id"]: r for r in produced}
        assert got["svc-021"]["waiver_id"] == "WV-2026-021"
        assert got["svc-021"]["status"] == "granted"
        assert got["svc-021"]["scope"] == "all"

    def test_matches_expected_register(self, produced, expected) -> None:
        """The full decoded register must match the ground-truth register."""
        got = {r["service_id"]: r for r in produced}
        exp = {r["service_id"]: r for r in expected}
        mismatches = {sid: (exp[sid], got.get(sid)) for sid in exp if got.get(sid) != exp[sid]}
        assert not mismatches, f"waiver records differ from expected: {mismatches}"
