#!/bin/bash
# Clean reinstall of the Snorkel submission monitor.
# Secrets live in tools/monitor/secrets.env (gitignored) — never commit that file.
set -euo pipefail

MONITOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$MONITOR_DIR/../.." && pwd)"
ENV_FILE="$MONITOR_DIR/.env"
SECRETS_FILE="$MONITOR_DIR/secrets.env"
STATE_DIR="$REPO_ROOT/.review-scratch/monitor"

echo "==> Snorkel monitor — clean setup"
echo "    repo: $REPO_ROOT"

if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "" >&2
  echo "Missing $SECRETS_FILE" >&2
  echo "Create it with (one line each):" >&2
  echo "  CURSOR_API_KEY=..." >&2
  echo "  TELEGRAM_BOT_TOKEN=..." >&2
  echo "  TELEGRAM_CHAT_ID=..." >&2
  echo "  TELEGRAM_ALLOWED_USER_IDS=...   # optional, same as chat id for DMs" >&2
  echo "" >&2
  echo "Copy from tools/monitor/secrets.env.example and fill in values." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$SECRETS_FILE"
set +a

for key in CURSOR_API_KEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID; do
  if [[ -z "${!key:-}" ]]; then
    echo "secrets.env is missing $key" >&2
    exit 1
  fi
done

: "${TELEGRAM_ALLOWED_USER_IDS:=${TELEGRAM_CHAT_ID}}"

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI required for GITHUB_TOKEN" >&2
  exit 1
fi
GITHUB_TOKEN="$(gh auth token)"
GITHUB_REPO_URL="${GITHUB_REPO_URL:-https://github.com/fabricenduwayo/fabre}"
GITHUB_BRANCH="${GITHUB_BRANCH:-$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)}"

echo "==> Stopping existing monitor jobs"
"$MONITOR_DIR/stop-all.sh" || true

if [[ -f "$STATE_DIR/state.json" ]]; then
  cp "$STATE_DIR/state.json" "$STATE_DIR/state.json.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  echo '{"runs":{},"last_states":{},"last_queue":{}}' > "$STATE_DIR/state.json"
  echo "==> Reset monitor state (backup saved)"
fi
rm -f "$STATE_DIR/.hourly.lock"

cat > "$ENV_FILE" <<EOF
# Snorkel submission monitor — generated by setup-clean.sh
# Secrets sourced from secrets.env (gitignored). Re-run setup-clean.sh after edits.

CURSOR_API_KEY=${CURSOR_API_KEY}

MONITOR_AGENT_RUNTIME=cloud
GITHUB_REPO_URL=${GITHUB_REPO_URL}
GITHUB_BRANCH=${GITHUB_BRANCH}
GITHUB_TOKEN=${GITHUB_TOKEN}
CLOUD_WORK_ON_BRANCH=1
CLOUD_USE_COMMIT_SHA=0
CLOUD_AGENT_RETRIES=3
CLOUD_AGENT_RETRY_SEC=45

NOTIFY_TELEGRAM=1
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
TELEGRAM_CMD_ENABLE=1
TELEGRAM_ALLOWED_USER_IDS=${TELEGRAM_ALLOWED_USER_IDS}

NOTIFY_MACOS=0

AUTO_AGENT_FIX=0
REQUIRE_CURSOR_OPEN=0
AUTO_GIT_COMMIT=1
ORACLE_PRECHECK=1
ORACLE_PRECHECK_TIMEOUT_SEC=900

NOTIFY_DIGEST=1
NOTIFY_PRIORITY_ONLY=0
NOTIFY_ON_IDLE=0
NOTIFY_QUIET_HOURS=1
NOTIFY_QUIET_START_HOUR=23
NOTIFY_QUIET_END_HOUR=7
MONITOR_TZ=America/Chicago
NOTIFY_DAILY_SUMMARY_HOUR_UTC=23

MAX_FIXES_PER_RUN=1
MAX_FIXES_PER_FORCE_RUN=3
MAX_FIXES_PER_DAY=8
MAX_AGENT_MINUTES_PER_DAY=180
MAX_ATTEMPTS_PER_FEEDBACK=3
FIX_COOLDOWN_SEC=3600
DEFAULT_PAUSE=6h

CURSOR_COMPOSER_MODEL=composer-2.5
COMMAND_POLL_SEC=20
GIT_WARN_MIN_FOLDERS=3

REPO_ROOT=${REPO_ROOT}
EOF
chmod 600 "$ENV_FILE"
echo "==> Wrote $ENV_FILE (branch=$GITHUB_BRANCH)"

echo "==> Installing venv + launchd"
if [[ ! -x "$MONITOR_DIR/.venv/bin/pip" ]]; then
  echo "    recreating broken venv"
  rm -rf "$MONITOR_DIR/.venv"
fi
"$MONITOR_DIR/install-hourly-launchd.sh"
"$MONITOR_DIR/install-command-listener.sh"

echo "==> Testing Telegram"
"$MONITOR_DIR/test-notify.sh"

echo "==> Dry-run scan (no Cursor agent)"
"$MONITOR_DIR/run-hourly.sh" --dry-run

echo ""
echo "Clean setup complete."
echo "  status:  $MONITOR_DIR/status-all.sh"
echo "  logs:    $STATE_DIR/monitor.log"
echo "  Telegram: message @nf_terminus_bot with: status | queue | run | dry-run"
echo ""
echo "Before cloud auto-fix works, confirm Cursor Dashboard → Integrations → GitHub"
echo "has access to fabricenduwayo/fabre. Keep Docker Desktop running."
