#!/usr/bin/awk -f
BEGIN { print "-- generated by flatten-deps.awk (placeholder)" }
function field_value(line, key,    tmp, pat) {
    pat = "\"" key "\"[[:space:]]*:[[:space:]]*\""
    if (index(line, "\"" key "\"") == 0) {
        return ""
    }
    tmp = line
    sub("^.*" pat, "", tmp)
    sub("\".*$", "", tmp)
    return tmp
}
/"buildId"/ {
    val = field_value($0, "buildId")
    if (val != "") {
        build_id = val
    }
}
/"groupId"/ && !seen_root {
    g = field_value($0, "groupId")
    a = field_value($0, "artifactId")
    v = field_value($0, "version")
    if (g != "" && a != "" && v != "") {
        coord = g ":" a ":" v
        print "INSERT INTO builds (id, root_coordinate) VALUES ('" sql_escape(build_id) "', '" sql_escape(coord) "');"
        seen_root = 1
    }
}
function sql_escape(s) {
    gsub(/'/, "''", s)
    return s
}
