version = "2.0"

[metadata]
author_name = "Fabrice Nduwayo"
author_email = "fabrice.nduwayo12@gmail.com"
difficulty = "hard"
category = "security"
subcategories = ["db_interaction"]
number_of_milestones = 3
codebase_size = "small"
languages = ["java", "bash", "sql"]
tags = ["security", "aes-gcm", "java", "sqlite", "jdbc"]
expert_time_estimate_min = 150
junior_time_estimate_min = 300

[environment]
allow_internet = false
build_timeout_sec = 1800.0
cpus = 2
memory_mb = 4096
storage_mb = 10240
workdir = "/app"

[verifier]
timeout_sec = 450.0

[agent]
timeout_sec = 1800.0

[[steps]]
name = "milestone_1"

[steps.agent]
timeout_sec = 1800.0

[steps.verifier]
timeout_sec = 450.0

[[steps]]
name = "milestone_2"

[steps.agent]
timeout_sec = 1800.0

[steps.verifier]
timeout_sec = 450.0

[[steps]]
name = "milestone_3"

[steps.agent]
timeout_sec = 1800.0

[steps.verifier]
timeout_sec = 450.0
